const $=s=>document.querySelector(s), tablet=$('#tablet'), cards=$('#cards'), history=$('#history'), employees=$('#employees'), employeeList=$('#employeeList');
let state={},active='service';
const post=(name,data={})=>fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json());
const safe=value=>{const e=document.createElement('span');e.textContent=value??'';return e.innerHTML};
function toast(message,ok=false){const el=$('#toast');el.textContent=message||'';el.className=ok?'ok':'bad';setTimeout(()=>el.textContent='',3500)}
function hide(){cards.classList.add('hidden');history.classList.add('hidden');employees.classList.add('hidden')}
function renderCards(type){hide();cards.classList.remove('hidden');cards.innerHTML='';const list=type==='products'?state.products:state.services.filter(x=>x.category===type);list.forEach(item=>{const card=document.createElement('article');card.className='card'+(item.locked?' locked':'');card.innerHTML=`<img src="${state.imageBase}${safe(item.image)}"><div><h2>${safe(item.label)}</h2><p>${type==='products'?'$'+item.price:(item.count||1)+'x '+safe(item.item)}</p><small>Vanaf rang ${item.minRank}</small></div><button ${item.locked?'disabled':''}>${item.locked?'Vergrendeld':type==='products'?'Kopen':'Start werk'}</button>`;card.querySelector('button').onclick=async()=>{if(type==='products'){const amount=Math.max(1,Number(prompt('Aantal',1))||1);const r=await post('buy',{name:item.name,amount});toast(r.message,r.success)}else post('service',{name:item.name})};cards.appendChild(card)})}
async function renderHistory(){hide();history.classList.remove('hidden');history.innerHTML='<div class="row head">Kenteken <span>Monteur</span><span>Werk</span><span>Datum</span></div>';for(const row of await post('history'))history.innerHTML+=`<div class="row">${safe(row.plate)}<span>${safe(row.mechanic_name)}</span><span>${safe(row.service_name)}</span><span>${safe(row.serviced_at)}</span></div>`}
function renderEmployees(){hide();employees.classList.remove('hidden');employeeList.innerHTML='';state.employees.forEach(person=>{const row=document.createElement('div');row.className='employee';const options=state.ranks.map(r=>`<option value="${r.id}" ${Number(person.rank)===r.id?'selected':''}>${safe(r.label)}</option>`).join('');row.innerHTML=`<div><b>${safe(person.player_name)}</b><small>${person.on_duty?'In dienst':'Uit dienst'}</small></div><select>${options}</select><button class="save">Opslaan</button><button class="fire">Ontslaan</button>`;row.querySelector('.save').onclick=async()=>{const r=await post('employee',{action:'setRank',target:person.identifier,rank:Number(row.querySelector('select').value)});toast(r.message,r.success);if(r.success)post('refresh')};row.querySelector('.fire').onclick=async()=>{if(confirm(`${person.player_name} ontslaan?`)){const r=await post('employee',{action:'fire',target:person.identifier});toast(r.message,r.success);if(r.success)post('refresh')}};employeeList.appendChild(row)})}
function tab(name){active=name;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if(name==='history')renderHistory();else if(name==='employees')renderEmployees();else renderCards(name)}
window.addEventListener('message',e=>{const d=e.data;if(d.action==='playSound'){const audio=new Audio(`sounds/${d.sound}.wav`);audio.volume=Math.max(0,Math.min(1,d.volume||0.6));audio.play().catch(()=>{});return}if(d.action==='hide')tablet.classList.add('hidden');if(d.action==='show'){state=d;$('#identity').textContent=`${d.profile.rankLabel} • ${d.profile.onDuty?'In dienst':'Uit dienst'}`;$('#duty').textContent=d.profile.onDuty?'Uit dienst':'In dienst';$('#plate').textContent=d.vehicle?.plate||'Geen motor';$('#engine').textContent=d.vehicle?`${d.vehicle.engine}%`:'-';$('#body').textContent=d.vehicle?`${d.vehicle.body}%`:'-';$('#employeeTab').classList.toggle('hidden',!d.profile.permissions.employees);tablet.classList.remove('hidden');tab(d.startTab||'service')}});
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('#close').onclick=()=>post('close');$('#duty').onclick=async()=>{const r=await post('duty');if(r.success)post('refresh')};$('#hire').onclick=async()=>{const r=await post('employee',{action:'hire',target:Number($('#hireId').value)});toast(r.message,r.success);if(r.success)post('refresh')};document.onkeydown=e=>{if(e.key==='Escape')post('close')};
